spring:
  profiles:
    active: dev
  redis:
    # Redis 数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    # Redis 服务器连接密码（默认为空）
    password:
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lxz
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用 druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: xianzhan.id.pojo.entity
  mapper-locations: classpath:mapper/*.xml